"""Render cached meshes generated by the submitted Terrain DR configuration.

The cache is produced by Isaac Lab's TerrainGenerator during the original runs.
This script replays its seed-10000 random tile selection, loads those OBJ meshes,
and renders a documentation preview. It does not approximate terrain geometry.
"""

from __future__ import annotations

from pathlib import Path
import re

import matplotlib

matplotlib.use("Agg")
from matplotlib import cm
import matplotlib.pyplot as plt
from matplotlib import font_manager
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np
import trimesh


ROOT = Path(__file__).resolve().parent
CACHE = Path("/tmp/isaaclab/terrains")
KOREAN_FONT = Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc")
FAMILIES = ("flat", "noise", "blocks", "slope")
FUNCTION_HINTS = {
    "flat": "flat_terrain",
    "noise": "curriculum_random_uniform_terrain",
    "blocks": "random_grid_terrain",
    "slope": "pyramid_sloped_terrain",
}


def cached_meshes() -> dict[str, list[tuple[float, Path]]]:
    """Index original seed-10000 cache entries by terrain family and difficulty."""
    found = {family: [] for family in FAMILIES}
    for cfg_path in CACHE.glob("*/cfg.yaml"):
        text = cfg_path.read_text()
        if "seed: 10000" not in text:
            continue
        difficulty = re.search(r"^difficulty: ([0-9.eE+-]+)$", text, re.MULTILINE)
        if difficulty is None:
            continue
        for family, hint in FUNCTION_HINTS.items():
            if hint in text:
                mesh_path = cfg_path.with_name("mesh.obj")
                if mesh_path.exists():
                    found[family].append((float(difficulty.group(1)), mesh_path))
                break
    if any(not entries for entries in found.values()):
        missing = ", ".join(family for family, entries in found.items() if not entries)
        raise FileNotFoundError(f"Original Isaac Lab terrain cache missing: {missing}")
    return found


def replay_first_tiles(index: dict[str, list[tuple[float, Path]]], count: int = 9):
    """Reproduce TerrainGenerator._generate_random_terrains for the first tile positions."""
    rng = np.random.default_rng(10_000)
    tiles = []
    for _ in range(count):
        family = FAMILIES[rng.choice(len(FAMILIES), p=(0.20, 0.30, 0.30, 0.20))]
        difficulty = rng.uniform(0.0, 0.60)
        _, path = min(index[family], key=lambda entry: abs(entry[0] - difficulty))
        tiles.append((family, difficulty, path))
    return tiles


def draw_mesh(ax, mesh_path: Path, *, translate=(0.0, 0.0), z_scale=5.0, label=None):
    mesh = trimesh.load(mesh_path, force="mesh", process=False)
    vertices = np.asarray(mesh.vertices, dtype=float).copy()
    vertices[:, :2] += translate
    vertices[:, 2] *= z_scale
    faces = np.asarray(mesh.faces)
    # The OBJ also stores the solid's underside and vertical collision walls.
    # Keep the physical top surface for this bird's-eye terrain preview.
    faces = faces[vertices[faces, 2].min(axis=1) > -0.10 * z_scale]
    # All faces are actual geometry; sparse rendering only avoids an unreadable dense surface.
    stride = max(1, len(faces) // 10_000)
    faces = faces[::stride]
    height = vertices[:, 2]
    norm = plt.Normalize(-0.08 * z_scale, 0.16 * z_scale)
    colors = cm.terrain(norm(height[faces].mean(axis=1)))
    collection = Poly3DCollection(vertices[faces], facecolors=colors, linewidths=0.0, antialiased=False)
    ax.add_collection3d(collection)
    if label:
        ax.text(translate[0] + 4, translate[1] + 4, 0.18 * z_scale, label, ha="center", va="bottom", fontsize=8)


def set_view(ax, title: str):
    ax.set_title(title, fontsize=10, pad=9)
    ax.set_xlabel("x (m)", labelpad=2, fontsize=8)
    ax.set_ylabel("y (m)", labelpad=2, fontsize=8)
    ax.set_zlabel("z ×5", labelpad=2, fontsize=8)
    ax.view_init(elev=40, azim=-55)
    ax.set_box_aspect((1, 1, 0.22))
    ax.tick_params(labelsize=7, pad=0)


def main():
    if KOREAN_FONT.exists():
        font_manager.fontManager.addfont(str(KOREAN_FONT))
        plt.rcParams["font.family"] = font_manager.FontProperties(fname=str(KOREAN_FONT)).get_name()
    index = cached_meshes()
    figure = plt.figure(figsize=(15, 9), layout="constrained")
    figure.suptitle("학습에 실제 사용된 Terrain DR mesh", x=0.02, ha="left", fontsize=20, fontweight="bold")
    figure.text(0.02, 0.935, "Isaac Lab cache · seed 10000 · 8 × 8 m tiles · z 축은 형태를 보기 위해 5배 확대", fontsize=11)

    grid = figure.add_gridspec(2, 4)
    mosaic = figure.add_subplot(grid[:, :2], projection="3d")
    for position, (family, difficulty, path) in enumerate(replay_first_tiles(index)):
        row, col = divmod(position, 3)
        draw_mesh(mosaic, path, translate=(row * 8.0 + 4.0, col * 8.0 + 4.0), label=f"{family}\nd={difficulty:.2f}")
    mosaic.set(xlim=(0, 24), ylim=(0, 24), zlim=(-0.12, 0.80))
    set_view(mosaic, "실제 생성 3 × 3 tile sample (generator 첫 9개 tile)")

    for plot_index, family in enumerate(FAMILIES):
        target_difficulty = 0.45
        difficulty, path = min(index[family], key=lambda entry: abs(entry[0] - target_difficulty))
        ax = figure.add_subplot(grid[plot_index // 2, 2 + plot_index % 2], projection="3d")
        draw_mesh(ax, path)
        ax.set(xlim=(-4, 4), ylim=(-4, 4), zlim=(-0.12, 0.80))
        set_view(ax, f"{family.title()} | d={difficulty:.2f}")

    figure.savefig(ROOT / "training_terrain_mesh.png", dpi=180)


if __name__ == "__main__":
    main()
